package:
  name: misoc
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  path: ../..

build:
  noarch_python: true
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}
  script: python setup.py install

requirements:
  build:
    - migen
    - python
  run:
    - migen
    - python
    - pyserial

test:
  imports:
    - misoc

about:
  home: https://m-labs.hk/gateware.html
  license: 3-clause BSD
  summary: 'A high performance and small footprint SoC based on Migen'
